//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ledger.SpamServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SpamServices.ISpam")]
    public interface ISpam {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpam/GetSpam", ReplyAction="http://tempuri.org/ISpam/GetSpamResponse")]
        string GetSpam();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpam/GetSpam", ReplyAction="http://tempuri.org/ISpam/GetSpamResponse")]
        System.Threading.Tasks.Task<string> GetSpamAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISpamChannel : Ledger.SpamServices.ISpam, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpamClient : System.ServiceModel.ClientBase<Ledger.SpamServices.ISpam>, Ledger.SpamServices.ISpam {
        
        public SpamClient() {
        }
        
        public SpamClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpamClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpamClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpamClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetSpam() {
            return base.Channel.GetSpam();
        }
        
        public System.Threading.Tasks.Task<string> GetSpamAsync() {
            return base.Channel.GetSpamAsync();
        }
    }
}
